gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We are just the healers\n"
	.string "here.\p"
	.string "Would you like heal??$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "What the hell?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen NO TRAINERS with\n"
	.string "a SILVER CARD before, let alone, {PLAYER},\l"
	.string "A DANG\l"
	.string "GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
